Installation et imports

In [1]:
!pip install yfinance

import yfinance as yf
import pandas as pd
from google.colab import files

Requirement already satisfied: yfinance in /usr/local/lib/python3.12/dist-packages (0.2.66)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.0.2)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.32.4)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.9.4)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.4.7)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.0.1)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.13.5)
Requirement already satisfied: curl_cffi>=0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.14.0)
Requirement already satisfied: protobuf>=3.19.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (5.29.6)
Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (15.0.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2026.2.25)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (2.5.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12.0->curl_cffi>=0.7->yfinance) (3.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)

Télécharger les données

In [2]:
tickers = ["E5H.SI","EB5.SI","P8Z.SI","5JS.SI","AALI.JK","LSIP.JK","SIMP.JK","SMAR.JK","TBLA.JK","UNSP.JK","SSMS.JK","BWPT.JK","DBA","MOO","RJA"]

data = yf.download(tickers, start="2015-01-01")["Close"]

data.head()

/tmp/ipykernel_414/38472778.py:3: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(tickers, start="2015-01-01")["Close"]
[*********************100%***********************]  15 of 15 completed

Ticker,5JS.SI,AALI.JK,BWPT.JK,DBA,E5H.SI,EB5.SI,LSIP.JK,MOO,P8Z.SI,RJA,SIMP.JK,SMAR.JK,SSMS.JK,TBLA.JK,UNSP.JK
Date,,,,,,,,,,,,,,,
2015-01-02,0.615186,16904.500000,397.0,21.180376,0.337494,1.239170,1323.021606,41.827995,0.560284,7.2900,580.742249,5272.602539,1274.376587,429.719788,500.0
2015-01-05,0.606759,16973.289062,395.0,21.438255,0.326489,1.229203,1340.384155,41.030972,0.560284,7.4300,576.681091,4565.301758,1289.457764,426.835602,500.0
2015-01-06,0.602545,16715.332031,390.0,21.584387,0.330158,1.225881,1319.549194,40.927353,0.560284,7.4301,568.558716,4404.551758,1289.457764,423.951630,500.0
2015-01-07,0.602545,16990.486328,382.0,21.481236,0.333826,1.255780,1329.966553,41.453396,0.552164,7.3900,564.497681,4693.901855,1289.457764,421.067657,500.0
2015-01-08,0.636254,17351.615234,383.0,21.403872,0.341163,1.308935,1402.889038,42.218544,0.562991,7.3699,588.864563,4693.901855,1289.457764,426.835602,500.0

Vérifier les données manquantes

In [3]:
data.isna().sum()

Ticker
5JS.SI      87
AALI.JK    140
BWPT.JK    141
DBA         84
E5H.SI      87
EB5.SI      87
LSIP.JK    141
MOO         84
P8Z.SI      87
RJA        910
SIMP.JK    141
SMAR.JK    140
SSMS.JK    149
TBLA.JK    140
UNSP.JK    140
dtype: int64

In [4]:
data = data.dropna()
data.isna().sum()

Ticker
5JS.SI     0
AALI.JK    0
BWPT.JK    0
DBA        0
E5H.SI     0
EB5.SI     0
LSIP.JK    0
MOO        0
P8Z.SI     0
RJA        0
SIMP.JK    0
SMAR.JK    0
SSMS.JK    0
TBLA.JK    0
UNSP.JK    0
dtype: int64

In [5]:
print("Dataset shape:", data.shape)
print("Date range:", data.index.min(), "to", data.index.max())

Dataset shape: (1869, 15)
Date range: 2015-01-02 00:00:00 to 2022-11-21 00:00:00

In [ ]:
data.describe()

Ticker,5JS.SI,AALI.JK,BWPT.JK,DBA,E5H.SI,EB5.SI,LSIP.JK,MOO,P8Z.SI,RJA,SIMP.JK,SMAR.JK,SSMS.JK,TBLA.JK,UNSP.JK
count,1869.000000,1869.000000,1869.000000,1869.000000,1869.000000,1869.000000,1869.000000,1869.000000,1869.000000,1869.000000,1869.000000,1869.000000,1869.000000,1869.000000,1869.000000
mean,0.337455,10186.669174,178.882825,16.281984,0.232780,1.215735,1006.030213,56.810860,0.403001,6.599919,397.788950,2921.924576,1032.708677,582.863779,241.655431
std,0.110397,2577.066944,89.088885,2.076199,0.057269,0.143510,155.168291,15.517680,0.070056,1.307306,83.657430,604.627425,275.506942,169.341742,173.275789
min,0.162709,3476.280273,57.000000,11.612879,0.102134,0.769694,426.348907,34.381046,0.224529,4.595000,154.052658,1775.419189,549.244385,252.146194,50.000000
25%,0.269138,8447.602539,99.000000,14.604488,0.193291,1.127457,918.741333,44.482098,0.360497,5.745000,353.363708,2528.560547,788.046326,472.036896,110.000000
50%,0.291566,9986.250977,166.000000,16.589827,0.238771,1.219756,1022.094055,53.334530,0.408039,6.280000,410.200867,2765.996338,1022.868225,592.783508,144.000000
75%,0.404104,11295.193359,234.000000,17.710524,0.279966,1.312659,1103.725708,65.717949,0.436519,6.900000,440.298981,3154.607422,1255.524658,664.348145,500.000000
max,0.665749,19236.595703,450.000000,21.584387,0.341163,1.743341,1402.889038,97.136993,0.582691,11.000000,613.231201,5272.603027,1813.882568,989.012268,800.000000

In [6]:
data.to_csv("palm_oil_dataset1.csv", index=True)

In [7]:
data = pd.read_csv("palm_oil_dataset1.csv", index_col=0, parse_dates=True)

data.head()

,5JS.SI,AALI.JK,BWPT.JK,DBA,E5H.SI,EB5.SI,LSIP.JK,MOO,P8Z.SI,RJA,SIMP.JK,SMAR.JK,SSMS.JK,TBLA.JK,UNSP.JK
Date,,,,,,,,,,,,,,,
2015-01-02,0.615186,16904.500000,397.0,21.180376,0.337494,1.239170,1323.021606,41.827995,0.560284,7.2900,580.742249,5272.602539,1274.376587,429.719788,500.0
2015-01-05,0.606759,16973.289062,395.0,21.438255,0.326489,1.229203,1340.384155,41.030972,0.560284,7.4300,576.681091,4565.301758,1289.457764,426.835602,500.0
2015-01-06,0.602545,16715.332031,390.0,21.584387,0.330158,1.225881,1319.549194,40.927353,0.560284,7.4301,568.558716,4404.551758,1289.457764,423.951630,500.0
2015-01-07,0.602545,16990.486328,382.0,21.481236,0.333826,1.255780,1329.966553,41.453396,0.552164,7.3900,564.497681,4693.901855,1289.457764,421.067657,500.0
2015-01-08,0.636254,17351.615234,383.0,21.403872,0.341163,1.308935,1402.889038,42.218544,0.562991,7.3699,588.864563,4693.901855,1289.457764,426.835602,500.0

In [8]:
files.download("palm_oil_dataset1.csv")